# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Jan 13 00:01:43 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.novayaZadachaKnopka = QtWidgets.QToolButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.novayaZadachaKnopka.sizePolicy().hasHeightForWidth())
        self.novayaZadachaKnopka.setSizePolicy(sizePolicy)
        self.novayaZadachaKnopka.setObjectName("novayaZadachaKnopka")
        self.horizontalLayout_3.addWidget(self.novayaZadachaKnopka)
        self.startStopKnopka = QtWidgets.QToolButton(self.centralWidget)
        self.startStopKnopka.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startStopKnopka.sizePolicy().hasHeightForWidth())
        self.startStopKnopka.setSizePolicy(sizePolicy)
        self.startStopKnopka.setObjectName("startStopKnopka")
        self.horizontalLayout_3.addWidget(self.startStopKnopka)
        self.novayaVlozhennayaZadacha = QtWidgets.QToolButton(self.centralWidget)
        self.novayaVlozhennayaZadacha.setObjectName("novayaVlozhennayaZadacha")
        self.horizontalLayout_3.addWidget(self.novayaVlozhennayaZadacha)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.derevoZadach = QtWidgets.QTreeWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.derevoZadach.sizePolicy().hasHeightForWidth())
        self.derevoZadach.setSizePolicy(sizePolicy)
        self.derevoZadach.setObjectName("derevoZadach")
        self.verticalLayout.addWidget(self.derevoZadach)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.kratkoeOpisanie = QtWidgets.QLineEdit(self.centralWidget)
        self.kratkoeOpisanie.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kratkoeOpisanie.sizePolicy().hasHeightForWidth())
        self.kratkoeOpisanie.setSizePolicy(sizePolicy)
        self.kratkoeOpisanie.setObjectName("kratkoeOpisanie")
        self.gridLayout.addWidget(self.kratkoeOpisanie, 1, 1, 1, 1)
        self.imyaZadachi = QtWidgets.QLineEdit(self.centralWidget)
        self.imyaZadachi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imyaZadachi.sizePolicy().hasHeightForWidth())
        self.imyaZadachi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.imyaZadachi.setFont(font)
        self.imyaZadachi.setObjectName("imyaZadachi")
        self.gridLayout.addWidget(self.imyaZadachi, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.minimumFlag = QtWidgets.QCheckBox(self.centralWidget)
        self.minimumFlag.setEnabled(False)
        self.minimumFlag.setObjectName("minimumFlag")
        self.gridLayout.addWidget(self.minimumFlag, 1, 2, 1, 1)
        self.maximumFlag = QtWidgets.QCheckBox(self.centralWidget)
        self.maximumFlag.setEnabled(False)
        self.maximumFlag.setObjectName("maximumFlag")
        self.gridLayout.addWidget(self.maximumFlag, 0, 2, 1, 1)
        self.maximumPeriod = QtWidgets.QTimeEdit(self.centralWidget)
        self.maximumPeriod.setEnabled(False)
        self.maximumPeriod.setObjectName("maximumPeriod")
        self.gridLayout.addWidget(self.maximumPeriod, 0, 3, 1, 1)
        self.minimumPeriod = QtWidgets.QTimeEdit(self.centralWidget)
        self.minimumPeriod.setEnabled(False)
        self.minimumPeriod.setObjectName("minimumPeriod")
        self.gridLayout.addWidget(self.minimumPeriod, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.detalnoeOpisanie = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.detalnoeOpisanie.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.detalnoeOpisanie.sizePolicy().hasHeightForWidth())
        self.detalnoeOpisanie.setSizePolicy(sizePolicy)
        self.detalnoeOpisanie.setObjectName("detalnoeOpisanie")
        self.verticalLayout.addWidget(self.detalnoeOpisanie)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 403, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.novayaZadachaMenu = QtWidgets.QAction(MainWindow)
        self.novayaZadachaMenu.setObjectName("novayaZadachaMenu")
        self.novayaVlozhennayaZadachaMenu = QtWidgets.QAction(MainWindow)
        self.novayaVlozhennayaZadachaMenu.setObjectName("novayaVlozhennayaZadachaMenu")
        self.udalitZadachuMenu = QtWidgets.QAction(MainWindow)
        self.udalitZadachuMenu.setObjectName("udalitZadachuMenu")
        self.menu.addAction(self.novayaZadachaMenu)
        self.menu.addAction(self.novayaVlozhennayaZadachaMenu)
        self.menu.addAction(self.udalitZadachuMenu)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Расписание"))
        self.novayaZadachaKnopka.setText(_translate("MainWindow", "Новая задача"))
        self.startStopKnopka.setText(_translate("MainWindow", "Старт/стоп"))
        self.novayaVlozhennayaZadacha.setText(_translate("MainWindow", "Новая вложенная задача"))
        self.derevoZadach.headerItem().setText(0, _translate("MainWindow", "Имя"))
        self.derevoZadach.headerItem().setText(1, _translate("MainWindow", "Всего"))
        self.derevoZadach.headerItem().setText(2, _translate("MainWindow", "Своё"))
        self.derevoZadach.headerItem().setText(3, _translate("MainWindow", "Максимум"))
        self.derevoZadach.headerItem().setText(4, _translate("MainWindow", "Минимум"))
        self.label.setText(_translate("MainWindow", "Название"))
        self.label_2.setText(_translate("MainWindow", "Описание"))
        self.minimumFlag.setText(_translate("MainWindow", "Минимум"))
        self.maximumFlag.setText(_translate("MainWindow", "Максимум"))
        self.menu.setTitle(_translate("MainWindow", "Задача"))
        self.novayaZadachaMenu.setText(_translate("MainWindow", "Создать"))
        self.novayaVlozhennayaZadachaMenu.setText(_translate("MainWindow", "Создать вложенную"))
        self.udalitZadachuMenu.setText(_translate("MainWindow", "Удалить"))

